#
# Example using JSON format
#
trigger:
  - master
pool:
  vmImage: "ubuntu-latest"
container: checkmarx/kics:debian
steps:
  # running in CI mode, exporting results to a JSON file and printing the results in stdout
  # KICS should fail the pipeline if results are found
  - script: |
      /app/bin/kics scan --ci -p ${PWD} -o ${PWD} --report-formats json
      cat results.json
