similarityIDChangeList:
    - queryId: 3847280c-9193-40bc-8009-76168e822ce2
      queryName: Undefined Scope 'securityDefinition' On 'security' Field On Operations
      observations: ""
      change: 1
    - queryId: 429b2106-ba37-43ba-9727-7f699cc611e1
      queryName: Unknown Property (v2)
      observations: Possibly fixed - Unable to reproduce the duplication issue, but added searchLine in hopes it resolves it
      change: 4
