name: go-generate-antlr-parser

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "pkg/parser/jsonfilter/JSONFilter.g4"
jobs:
  metrics:
    name: generate-antlr-parser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build ANTLR image
        uses: docker/build-push-action@v3.1.1
        id: build_antlr_image
        with:
          context: .
          push: false
          tags: antlr4-generator:dev
      - name: Generate Parser
        run: |
          docker run --rm -u $(id -u ${USER}):$(id -g ${USER}) -v $(pwd)/pkg/parser/jsonfilter:/work -it antlr4-generator:dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "chore(parser): updating AWS jsonfilter ANTLR generated parser"
          token: ${{ secrets.KICS_BOT_PAT }}
          commit-message: "chore(parser): updating AWS jsonfilter ANTLR generated parser"
          delete-branch: true
          branch: feature/kicsbot-update-jsonfilter-parser
          body: |
            **Automated Changes**
            Updating ANTLR generated parser after grammar changes
            Triggered by SHA: _${{ github.sha }}_
          labels: go
