name: go-generate-antlr-parser

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "pkg/parser/jsonfilter/JSONFilter.g4"
jobs:
  metrics:
    name: generate-antlr-parser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Build ANTLR image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: build_antlr_image
        with:
          context: .
          push: false
          tags: antlr4-generator:dev
      - name: Generate Parser
        run: |
          docker run --rm -u $(id -u ${USER}):$(id -g ${USER}) -v $(pwd)/pkg/parser/jsonfilter:/work -it antlr4-generator:dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v6
        with:
          title: "chore(parser): updating AWS jsonfilter ANTLR generated parser"
          token: ${{ secrets.KICS_BOT_PAT }}
          commit-message: "chore(parser): updating AWS jsonfilter ANTLR generated parser"
          delete-branch: true
          branch: feature/kicsbot-update-jsonfilter-parser
          body: |
            **Automated Changes**
            Updating ANTLR generated parser after grammar changes
            Triggered by SHA: _${{ github.sha }}_
          labels: go
