name: release-manual-docker-tag-latest

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git Tag"
        required: true
      latest:
        description: "true if image is latest"
        default: "false"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.KICS_BOT_PAT }}
          webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK_URL }}
          card-layout-start: cozy
          card-layout-exit: complete
          show-on-start: true
          show-on-exit: true
          custom-actions: |
            - name: View CI Logs
              value: https://github.com/Checkmarx/kics/actions/runs/${{ github.run_id }}
            - name: View HEAD Commit
              value: https://github.com/Checkmarx/kics/commit/${{ github.sha }}
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=Checkmarx/kics
          VERSION=${{ github.event.inputs.tag }}
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          ALPINE_TAGS="${TAGS}-alpine"
          DEBIAN_TAGS="${TAGS}-debian"
          UBI8_TAGS="${TAGS}-ubi8"

          if [ "${{ github.event.inputs.latest }}" = "true" ]; then
            TAGS=${TAGS},${DOCKER_IMAGE}:latest
            ALPINE_TAGS="{ALPINE_TAGS},${DOCKER_IMAGE}:alpine"
            DEBIAN_TAGS="{DEBIAN_TAGS},${DOCKER_IMAGE}:debian"
            UBI8_TAGS="{UBI8_TAGS},${DOCKER_IMAGE}:ubi8"
          fi

          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=alpine_tags::${ALPINE_TAGS}
          echo ::set-output name=debian_tags::${DEBIAN_TAGS}
          echo ::set-output name=ubi8_tags::${UBI8_TAGS}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push alpine to Docker Hub
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.prep.outputs.tags }},${{ steps.prep.outputs.alpine_tags }}
          build-args: |
            VERSION=${{ github.event.inputs.tag }}
            COMMIT=${{ github.sha }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            DESCRIPTIONS_URL=${{ secrets.DESCRIPTIONS_URL }}
      - name: Push debian to Docker Hub
        if: ${{ hashFiles('./docker/Dockerfile.debian') }} != ""
        id: build_debian
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./docker/Dockerfile.debian
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.prep.outputs.debian_tags }}
          build-args: |
            VERSION=${{ github.event.inputs.tag }}
            COMMIT=${{ github.sha }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            DESCRIPTIONS_URL=${{ secrets.DESCRIPTIONS_URL }}
      - name: Push ubi8 to Docker Hub
        if: ${{ hashFiles('./docker/Dockerfile.ubi8') }} != ""
        id: build_ubi8
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./docker/Dockerfile.ubi8
          push: true
          platforms: linux/amd64
          tags: ${{ steps.prep.outputs.ubi8_tags }}
          build-args: |
            VERSION=${{ github.event.inputs.tag }}
            COMMIT=${{ github.sha }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            DESCRIPTIONS_URL=${{ secrets.DESCRIPTIONS_URL }}
