name: update-infra-version

on:
  workflow_dispatch:
  release:
    type: [published]

jobs:
  update-infra-version:
    name: Updates infra with new release
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    steps:
      - name: Checkout project
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
      - name: Update Terraform Cloud Integration
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v3
        with:
          token: ${{ secrets.KICS_BOT_PAT }}
          repository: ${{ secrets.TFC_REPO_PATH }}
          event-type: new-release
      - name: Update Infra
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v3
        with:
          token: ${{ secrets.KICS_BOT_PAT }}
          repository: ${{ secrets.INFRA_REPO }}
          event-type: new-release
