name: validate-k8s-samples

on:
  pull_request:
    paths:
      - "assets/queries/k8s/**/test/*.yaml"
      - "assets/queries/k8s/**/test/*.yml"

jobs:
  validate-k8s-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Get Kubeconform
        env:
          KUBECONFORM_VERSION: v0.6.4
        run: |
          mkdir -p .bin
          PROJDIR=$(pwd)
          cd .bin && wget "https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz" \
            && tar xf kubeconform-linux-amd64.tar.gz \
            && chmod +x kubeconform \
            && rm -vf kubeconform-linux-amd64.tar.gz \
            && cd "${PROJDIR}"
      - name: Validate k8s manifests
        run: |
          python3 -u .github/scripts/samples-linters/validate-syntax.py \
            "assets/queries/k8s/**/test/*.yaml" \
            --extra ' -skip CustomResourceDefinition,KubeletConfiguration,Policy,EncryptionConfiguration,KubeSchedulerConfiguration,SecretProviderClass,Service,Configuration,ContainerSource,Revision,PodSecurityPolicy' \
            --linter .bin/kubeconform \
            --skip '.github/scripts/samples-linters/ignore-list/k8s' -v
